import { createHash } from "node:crypto";
import { lstatSync, realpathSync, statSync } from "node:fs";
import { resolve } from "node:path";
import Database from "better-sqlite3";

export const AMBIENT_MEMORY_CLEANUP_SCOPES = [
  { guildId: "1508658440736604230", channelId: "1508659103637966858" },
  { guildId: "1483095221460799489", channelId: "1498703634098294976" },
] as const;
export type AmbientMemoryCleanupScope = { readonly guildId: string; readonly channelId: string };
export type AmbientMemoryCleanupDatabase = { readonly db: Database.Database };
type CleanupOptions = { readonly scopes?: readonly AmbientMemoryCleanupScope[] };
type ScopeInventory = { readonly guildId: string; readonly channelId: string; readonly scopeId: string; readonly archiveBatchCount: number; readonly archiveSummaryCount: number; readonly archiveMarkerCount: number; readonly legacySummaryCount: number; readonly relationshipProfileCount: number; readonly relationshipLedgerCount: number; readonly rawEventCount: number; readonly fullyProcessedRawEventCount: number; readonly retainedRawEventCount: number; readonly rawPruneCount: number; readonly protectedTickRawEventCount: number; readonly nonTerminalWorkRawEventCount: number; readonly pendingDeliveryRawEventCount: number; readonly claimedArchiveBatchCount: number };
export type AmbientMemoryCleanupInventory = { readonly schema: "hent_ai.ambient_memory_cleanup.inventory.v2"; readonly scopes: readonly ScopeInventory[]; readonly claimedWorkCount: number; readonly blockers: readonly string[]; readonly ready: boolean };
export type AmbientMemoryCleanupDeleted = { readonly archiveBatches: number; readonly archiveSummaries: number; readonly archiveMarkers: number; readonly legacySummaries: number; readonly relationshipProfiles: number; readonly relationshipLedger: number; readonly receipts: number; readonly deliveryChunks: number; readonly plans: number; readonly validations: number; readonly primaryChunks: number; readonly snapshotTurns: number; readonly clearedTerminalWorkTickIds: number; readonly coverage: number; readonly ticks: number; readonly terminalWork: number; readonly rawEvents: number; readonly skippedProtectedTickAnchorWork: number; readonly skippedProtectedTickHighWatermarkRaw: number; readonly skippedProtectedSnapshotRaw: number; readonly skippedProtectedPlan: number; readonly skippedProtectedReplyAncestor: number };
export type AmbientMemoryCleanupApplyResult = { readonly inventory: AmbientMemoryCleanupInventory; readonly deleted: AmbientMemoryCleanupDeleted; readonly backupFingerprint: string };
export type AmbientMemoryCleanupApplyOptions = CleanupOptions & { readonly db: AmbientMemoryCleanupDatabase; readonly backupPath: string; readonly signal?: AbortSignal; readonly beforeCommit?: () => void };

const terminal = "'observe','delivered','covered'";
export function inventoryAmbientMemoryCleanup(db: AmbientMemoryCleanupDatabase, options: CleanupOptions = {}): AmbientMemoryCleanupInventory {
  const scopes = cleanupScopes(options.scopes); const blockers = [...settingsBlockers(db.db, scopes)];
  const claimedWorkCount = count(db.db, "SELECT COUNT(*) AS count FROM participant_event_work WHERE status='claimed'");
  if (claimedWorkCount) blockers.push(`claimed work exists (${claimedWorkCount})`);
  const inventory = scopes.map((scope) => inventoryScope(db.db, scope));
  if (inventory.some((item) => item.claimedArchiveBatchCount)) blockers.push("claimed archive batch exists in a selected scope");
  return { schema: "hent_ai.ambient_memory_cleanup.inventory.v2", scopes: inventory, claimedWorkCount, blockers, ready: blockers.length === 0 };
}
export function applyAmbientMemoryCleanup(options: AmbientMemoryCleanupApplyOptions): AmbientMemoryCleanupApplyResult {
  const scopes = cleanupScopes(options.scopes); aborted(options.signal); const preflight = inventoryAmbientMemoryCleanup(options.db, { scopes });
  if (!preflight.ready) throw new Error(`cleanup preconditions failed: ${preflight.blockers.join("; ")}`);
  const backupFingerprint = verifyBackup(options.db.db, options.backupPath); options.db.db.exec("BEGIN IMMEDIATE");
  try { aborted(options.signal); if (fingerprint(options.db.db) !== backupFingerprint) throw new Error("backup does not match the current SQLite database");
    const inventory = inventoryAmbientMemoryCleanup(options.db, { scopes }); if (!inventory.ready) throw new Error(`cleanup preconditions failed: ${inventory.blockers.join("; ")}`);
    const deleted = deleteSelectedMemory(options.db.db, scopes, Date.now()); aborted(options.signal); options.beforeCommit?.(); aborted(options.signal); options.db.db.exec("COMMIT"); return { inventory, deleted, backupFingerprint };
  } catch (error) { options.db.db.exec("ROLLBACK"); throw error; }
}
export function fingerprintAmbientMemoryCleanupDatabase(db: AmbientMemoryCleanupDatabase, options: { readonly scopeIds?: readonly string[] } = {}): string { return fingerprint(db.db, options.scopeIds); }
function inventoryScope(db: Database.Database, scope: AmbientMemoryCleanupScope): ScopeInventory {
  const id = scopeId(scope); const eligible = eligibleSql("COUNT(*) AS count");
  const rawEventCount = count(db, "SELECT COUNT(*) AS count FROM conversation_raw_events WHERE scope_id=? AND author_source='discord-participant'", id);
  const fullyProcessedRawEventCount = count(db, eligible, id, scope.guildId, scope.channelId, scope.guildId, scope.channelId);
  const rawPruneCount = count(db, `SELECT COUNT(*) AS count FROM (${eligibleSql("r.id,ROW_NUMBER() OVER (ORDER BY r.event_ts DESC,r.id DESC) AS n")}) WHERE n>20`, id, scope.guildId, scope.channelId, scope.guildId, scope.channelId);
  return { guildId: scope.guildId, channelId: scope.channelId, scopeId: id,
    archiveBatchCount: count(db, "SELECT COUNT(*) AS count FROM conversation_archive_batches WHERE scope_id=?", id), archiveSummaryCount: count(db, "SELECT COUNT(*) AS count FROM conversation_archive_summaries s JOIN conversation_archive_batches b ON b.batch_key=s.batch_key WHERE b.scope_id=?", id), archiveMarkerCount: count(db, "SELECT COUNT(*) AS count FROM conversation_raw_archive_markers m JOIN conversation_archive_batches b ON b.batch_key=m.batch_key WHERE b.scope_id=?", id), legacySummaryCount: count(db, "SELECT COUNT(*) AS count FROM conversation_summaries WHERE scope_id=?", id), relationshipProfileCount: count(db, "SELECT COUNT(*) AS count FROM adaptive_relationship_profiles WHERE guild_id=? AND channel_id=?", scope.guildId, scope.channelId), relationshipLedgerCount: count(db, "SELECT COUNT(*) AS count FROM adaptive_relationship_ledger WHERE guild_id=? AND channel_id=?", scope.guildId, scope.channelId), rawEventCount, fullyProcessedRawEventCount, retainedRawEventCount: Math.min(20, fullyProcessedRawEventCount), rawPruneCount,
    protectedTickRawEventCount: count(db, `SELECT COUNT(*) AS count FROM conversation_raw_events r WHERE r.scope_id=? AND r.author_source='discord-participant' AND (EXISTS (SELECT 1 FROM conversation_participation_ticks t WHERE t.snapshot_high_watermark_id=r.id) OR EXISTS (SELECT 1 FROM conversation_participation_snapshot_turns s WHERE s.raw_event_id=r.id))`, id),
    nonTerminalWorkRawEventCount: count(db, `SELECT COUNT(*) AS count FROM conversation_raw_events r WHERE r.scope_id=? AND r.author_source='discord-participant' AND EXISTS (SELECT 1 FROM participant_event_work w WHERE w.event_id=r.message_id AND w.guild_id=? AND w.channel_id=? AND w.status NOT IN (${terminal}))`, id, scope.guildId, scope.channelId), pendingDeliveryRawEventCount: count(db, `SELECT COUNT(*) AS count FROM conversation_raw_events r WHERE r.scope_id=? AND r.author_source='discord-participant' AND EXISTS (SELECT 1 FROM participant_event_work w JOIN participant_delivery_plans p ON p.work_id=w.id AND p.status IN ('pending','retryable') WHERE w.event_id=r.message_id AND w.guild_id=? AND w.channel_id=?)`, id, scope.guildId, scope.channelId), claimedArchiveBatchCount: count(db, "SELECT COUNT(*) AS count FROM conversation_archive_batches WHERE scope_id=? AND status='claimed'", id) };
}
function deleteSelectedMemory(db: Database.Database, scopes: readonly AmbientMemoryCleanupScope[], now: number): AmbientMemoryCleanupDeleted {
  const ids = scopes.map(scopeId); const placeholders = ids.map(() => "?").join(","); const where = scopes.map(() => "(guild_id=? AND channel_id=?)").join(" OR "); const tickWhere = scopes.map(() => "(t.guild_id=? AND t.channel_id=?)").join(" OR "); const args = scopes.flatMap((s) => [s.guildId, s.channelId]); const rawWorkWhere = rawWorkScopeWhere(scopes); const rawWorkArgs = scopes.flatMap((s) => [s.guildId, s.channelId, scopeId(s)]); const cutoff = now - 7 * 24 * 60 * 60 * 1000;
  const protectedTicks = `SELECT t.id FROM conversation_participation_ticks t LEFT JOIN conversation_participation_validations v ON v.tick_id=t.id LEFT JOIN participant_delivery_plans p ON p.tick_id=t.id AND p.decision_version='v2' WHERE (${tickWhere}) AND (t.status NOT IN ('validated','validation_unavailable','snapshot_corrupt','aborted') OR (t.status IN ('validated','validation_unavailable') AND COALESCE(v.status,'') NOT IN ('applied','accepted_shadow','unavailable')) OR EXISTS (SELECT 1 FROM participant_delivery_plans q WHERE q.tick_id=t.id AND q.decision_version='v2' AND q.status IN ('pending','retryable')) OR EXISTS (SELECT 1 FROM participant_delivery_plans q JOIN participant_delivery_chunks c ON c.plan_id=q.id LEFT JOIN participant_delivery_receipts r ON r.plan_id=c.plan_id AND r.chunk_index=c.chunk_index WHERE q.tick_id=t.id AND q.decision_version='v2' AND r.plan_id IS NULL) OR t.updated_at_ms>=? OR COALESCE(v.updated_at_ms,0)>=? OR COALESCE(p.updated_at_ms,0)>=?)`;
  const eligibleTicks = `SELECT t.id FROM conversation_participation_ticks t WHERE (${where}) AND t.status IN ('validated','validation_unavailable','snapshot_corrupt','aborted') AND t.id NOT IN (${protectedTicks})`;
  const protectedArgs = [...args, cutoff, cutoff, cutoff]; const eligibleArgs = [...args, ...protectedArgs];
  const eligibleTickIds = (db.prepare(eligibleTicks).all(...eligibleArgs) as { id: string }[]).map((row) => row.id);
  const eligibleTickSql = eligibleTickIds.length ? eligibleTickIds.map(() => "?").join(",") : "NULL";
  const rawEligible = `SELECT r.id FROM conversation_raw_events r WHERE r.scope_id IN (${placeholders}) AND r.author_source='discord-participant' AND (SELECT COUNT(*) FROM conversation_raw_events newer WHERE newer.scope_id=r.scope_id AND newer.author_source='discord-participant' AND (newer.event_ts>r.event_ts OR (newer.event_ts=r.event_ts AND newer.id>r.id)))>=20 AND EXISTS (SELECT 1 FROM participant_event_work w WHERE w.event_id=r.message_id AND (${rawWorkWhere}) AND w.status IN (${terminal})) AND NOT EXISTS (SELECT 1 FROM conversation_participation_ticks t JOIN participant_event_work w ON w.id=t.anchor_work_id WHERE w.event_id=r.message_id AND (${rawWorkWhere}) AND t.id IN (${protectedTicks})) AND NOT EXISTS (SELECT 1 FROM conversation_participation_ticks t WHERE t.snapshot_high_watermark_id=r.id AND t.id IN (${protectedTicks})) AND NOT EXISTS (SELECT 1 FROM conversation_participation_snapshot_turns s JOIN conversation_participation_ticks t ON t.id=s.tick_id WHERE s.raw_event_id=r.id AND t.id IN (${protectedTicks})) AND NOT EXISTS (SELECT 1 FROM participant_delivery_plans p JOIN participant_event_work w ON w.id=p.work_id WHERE w.event_id=r.message_id AND (${rawWorkWhere}) AND p.decision_version='v2' AND p.status IN ('pending','retryable')) AND NOT EXISTS (SELECT 1 FROM conversation_participation_coverage c JOIN participant_event_work w ON w.id=c.work_id WHERE w.event_id=r.message_id AND (${rawWorkWhere})) AND NOT EXISTS (SELECT 1 FROM conversation_raw_archive_markers m WHERE m.raw_event_id=r.id) AND NOT EXISTS (SELECT 1 FROM conversation_raw_events child WHERE child.scope_id=r.scope_id AND child.author_source='discord-participant' AND json_extract(child.metadata_json,'$.replyTo.messageId')=r.message_id)`;
  const rawArgs = [...ids, ...rawWorkArgs, ...rawWorkArgs, ...protectedArgs, ...protectedArgs, ...protectedArgs, ...rawWorkArgs, ...rawWorkArgs];
  const rawIds = db.prepare(`SELECT id FROM (${rawEligible}) ORDER BY id`).all(...rawArgs).map((r) => Number((r as { id:number }).id));
  const skippedProtectedTickAnchorWork = count(db, `SELECT COUNT(*) AS count FROM conversation_raw_events r WHERE r.scope_id IN (${placeholders}) AND r.author_source='discord-participant' AND EXISTS (SELECT 1 FROM conversation_participation_ticks t JOIN participant_event_work w ON w.id=t.anchor_work_id WHERE w.event_id=r.message_id AND (${rawWorkWhere}) AND t.id IN (${protectedTicks}))`, ...ids, ...rawWorkArgs, ...protectedArgs);
  const skippedProtectedTickHighWatermarkRaw = count(db, `SELECT COUNT(*) AS count FROM conversation_raw_events r WHERE r.scope_id IN (${placeholders}) AND r.author_source='discord-participant' AND EXISTS (SELECT 1 FROM conversation_participation_ticks t WHERE t.snapshot_high_watermark_id=r.id AND t.id IN (${protectedTicks}))`, ...ids, ...protectedArgs);
  const skippedProtectedSnapshotRaw = count(db, `SELECT COUNT(*) AS count FROM conversation_raw_events r WHERE r.scope_id IN (${placeholders}) AND r.author_source='discord-participant' AND EXISTS (SELECT 1 FROM conversation_participation_snapshot_turns s JOIN conversation_participation_ticks t ON t.id=s.tick_id WHERE s.raw_event_id=r.id AND t.id IN (${protectedTicks}))`, ...ids, ...protectedArgs);
  const skippedProtectedPlan = count(db, `SELECT COUNT(*) AS count FROM conversation_raw_events r WHERE r.scope_id IN (${placeholders}) AND r.author_source='discord-participant' AND (EXISTS (SELECT 1 FROM participant_delivery_plans p JOIN participant_event_work w ON w.id=p.work_id WHERE w.event_id=r.message_id AND (${rawWorkWhere}) AND p.decision_version='v2' AND p.status IN ('pending','retryable')) OR EXISTS (SELECT 1 FROM conversation_participation_coverage c JOIN participant_event_work w ON w.id=c.work_id WHERE w.event_id=r.message_id AND (${rawWorkWhere})))`, ...ids, ...rawWorkArgs, ...rawWorkArgs);
  const skippedProtectedReplyAncestor = count(db, `SELECT COUNT(*) AS count FROM conversation_raw_events r WHERE r.scope_id IN (${placeholders}) AND r.author_source='discord-participant' AND EXISTS (SELECT 1 FROM conversation_raw_events child WHERE child.scope_id=r.scope_id AND child.author_source='discord-participant' AND json_extract(child.metadata_json,'$.replyTo.messageId')=r.message_id)`, ...ids);
  const receipts = changes(db, `DELETE FROM participant_delivery_receipts WHERE plan_id IN (SELECT id FROM participant_delivery_plans WHERE tick_id IN (${eligibleTickSql}) AND decision_version='v2')`, ...eligibleTickIds);
  const deliveryChunks = changes(db, `DELETE FROM participant_delivery_chunks WHERE plan_id IN (SELECT id FROM participant_delivery_plans WHERE tick_id IN (${eligibleTickSql}) AND decision_version='v2')`, ...eligibleTickIds);
  const plans = changes(db, `DELETE FROM participant_delivery_plans WHERE tick_id IN (${eligibleTickSql}) AND decision_version='v2'`, ...eligibleTickIds);
  const validations = changes(db, `DELETE FROM conversation_participation_validations WHERE tick_id IN (${eligibleTickSql})`, ...eligibleTickIds);
  const primaryChunks = changes(db, `DELETE FROM conversation_participation_primary_chunks WHERE tick_id IN (${eligibleTickSql})`, ...eligibleTickIds);
  const snapshotTurns = changes(db, `DELETE FROM conversation_participation_snapshot_turns WHERE tick_id IN (${eligibleTickSql})`, ...eligibleTickIds);
  const clearedTerminalWorkTickIds = changes(db, `UPDATE participant_event_work SET participation_tick_id=NULL WHERE participation_tick_id IN (${eligibleTickSql})`, ...eligibleTickIds);
  const coverage = changes(db, `DELETE FROM conversation_participation_coverage WHERE tick_id IN (${eligibleTickSql})`, ...eligibleTickIds);
  const ticks = changes(db, `DELETE FROM conversation_participation_ticks WHERE id IN (${eligibleTickSql})`, ...eligibleTickIds);
  const terminalWork = changes(db, `DELETE FROM participant_event_work WHERE (${where}) AND status IN (${terminal}) AND participation_tick_id IS NULL AND NOT EXISTS (SELECT 1 FROM participant_delivery_plans p WHERE p.work_id=participant_event_work.id) AND NOT EXISTS (SELECT 1 FROM conversation_participation_ticks t WHERE t.anchor_work_id=participant_event_work.id)`, ...args);
  const archiveSummaries = changes(db, `DELETE FROM conversation_archive_summaries WHERE batch_key IN (SELECT batch_key FROM conversation_archive_batches WHERE scope_id IN (${placeholders}))`, ...ids);
  const archiveMarkers = changes(db, `DELETE FROM conversation_raw_archive_markers WHERE batch_key IN (SELECT batch_key FROM conversation_archive_batches WHERE scope_id IN (${placeholders}))`, ...ids);
  const archiveBatches = changes(db, `DELETE FROM conversation_archive_batches WHERE scope_id IN (${placeholders})`, ...ids);
  const legacySummaries = changes(db, `DELETE FROM conversation_summaries WHERE scope_id IN (${placeholders})`, ...ids);
  const relationshipLedger = changes(db, `DELETE FROM adaptive_relationship_ledger WHERE ${where}`, ...args);
  const relationshipProfiles = changes(db, `DELETE FROM adaptive_relationship_profiles WHERE ${where}`, ...args);
  const rawEvents = rawIds.length ? changes(db, `DELETE FROM conversation_raw_events
    WHERE id IN (${rawIds.map(() => "?").join(",")})
      AND NOT EXISTS (SELECT 1 FROM conversation_participation_ticks t WHERE t.snapshot_high_watermark_id=conversation_raw_events.id)
      AND NOT EXISTS (SELECT 1 FROM conversation_participation_snapshot_turns s WHERE s.raw_event_id=conversation_raw_events.id)
      AND NOT EXISTS (SELECT 1 FROM conversation_raw_archive_markers m WHERE m.raw_event_id=conversation_raw_events.id)`, ...rawIds) : 0;
  return { archiveBatches, archiveSummaries, archiveMarkers, legacySummaries, relationshipProfiles, relationshipLedger, receipts, deliveryChunks, plans, validations, primaryChunks, snapshotTurns, clearedTerminalWorkTickIds, coverage, ticks, terminalWork, rawEvents, skippedProtectedTickAnchorWork, skippedProtectedTickHighWatermarkRaw, skippedProtectedSnapshotRaw, skippedProtectedPlan, skippedProtectedReplyAncestor };
}
function eligibleSql(select: string): string { return `SELECT ${select} FROM conversation_raw_events r WHERE r.scope_id=? AND r.author_source='discord-participant' AND EXISTS (SELECT 1 FROM participant_event_work w WHERE w.event_id=r.message_id AND w.guild_id=? AND w.channel_id=? AND w.status IN (${terminal})) AND NOT EXISTS (SELECT 1 FROM participant_event_work w JOIN participant_delivery_plans p ON p.work_id=w.id AND p.status IN ('pending','retryable') WHERE w.event_id=r.message_id AND w.guild_id=? AND w.channel_id=?) AND NOT EXISTS (SELECT 1 FROM conversation_participation_ticks t WHERE t.snapshot_high_watermark_id=r.id) AND NOT EXISTS (SELECT 1 FROM conversation_participation_snapshot_turns s WHERE s.raw_event_id=r.id)`; }
function rawWorkScopeWhere(scopes: readonly AmbientMemoryCleanupScope[]): string { return scopes.map(() => "(w.guild_id=? AND w.channel_id=? AND r.scope_id=?)").join(" OR "); }
function settingsBlockers(db: Database.Database, scopes: readonly AmbientMemoryCleanupScope[]): string[] { const blockers: string[]=[]; for (const scope of scopes) { const row=db.prepare("SELECT settings_json FROM channel_settings WHERE channel_id=?").get(scope.channelId) as {settings_json:unknown}|undefined; try { if (!row || typeof row.settings_json!=="string" || (JSON.parse(row.settings_json) as {ambientMemoryMode?:unknown}).ambientMemoryMode!=="external") throw new Error(); } catch { blockers.push(`external memory settings required for ${scopeId(scope)}`); } } return blockers; }
function cleanupScopes(input: readonly AmbientMemoryCleanupScope[] | undefined): readonly AmbientMemoryCleanupScope[] { const scopes=input ?? AMBIENT_MEMORY_CLEANUP_SCOPES; const expected=new Set(AMBIENT_MEMORY_CLEANUP_SCOPES.map(scopeId)); if (scopes.length!==2 || new Set(scopes.map(scopeId)).size!==2 || scopes.some((s)=>!expected.has(scopeId(s)))) throw new Error("cleanup requires exactly the two approved guild/channel scope IDs"); return AMBIENT_MEMORY_CLEANUP_SCOPES; }
function verifyBackup(source: Database.Database, backupPath: string): string { const sourceFingerprint=fingerprint(source); const path=resolve(backupPath); if (lstatSync(path).isSymbolicLink()) throw new Error("SQLite backup path must not be a symbolic link"); const sourcePath=(source.pragma("database_list") as {file?:unknown;name?:unknown}[]).find((x)=>x.name==="main")?.file; if (typeof sourcePath==="string" && sourcePath) { const a=statSync(realpathSync(sourcePath)), b=statSync(path); if (a.dev===b.dev && a.ino===b.ino) throw new Error("SQLite backup path must differ from the database being cleaned"); } const backup=new Database(path,{readonly:true,fileMustExist:true}); try { if (backup.pragma("integrity_check",{simple:true})!=="ok") throw new Error("SQLite backup integrity check failed"); if (fingerprint(backup)!==sourceFingerprint) throw new Error("backup does not match the current SQLite database"); return sourceFingerprint; } finally { backup.close(); } }
function fingerprint(db: Database.Database, scopeIds?: readonly string[]): string { const hash=createHash("sha256"); const schema=db.prepare("SELECT type,name,tbl_name,sql FROM sqlite_master WHERE type IN ('table','index','trigger','view') AND name NOT LIKE 'sqlite_%' ORDER BY type,name,tbl_name").all(); hash.update(JSON.stringify(schema)); for (const table of db.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all() as {name:string}[]) { const quoted=`\"${table.name.replaceAll('"','""')}\"`; const rows=db.prepare(`SELECT * FROM ${quoted}`).all().map(normalize).map((row) => JSON.stringify(row)).sort(); hash.update(JSON.stringify([table.name,rows])); } return hash.digest("hex"); }
function normalize(value: unknown): unknown { if (Buffer.isBuffer(value)) return { binary:value.toString("base64") }; if (Array.isArray(value)) return value.map(normalize); if (value && typeof value==="object") return Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,normalize(v)])); return value; }
function scopeId(scope: AmbientMemoryCleanupScope): string { return `discord:${scope.guildId}:${scope.channelId}`; } function count(db: Database.Database, sql:string,...args:unknown[]):number { return Number((db.prepare(sql).get(...args) as {count:number}).count); } function changes(db: Database.Database, sql:string,...args:unknown[]):number { return db.prepare(sql).run(...args).changes; } function aborted(signal: AbortSignal|undefined):void { if(signal?.aborted) throw new Error("cleanup aborted"); }
