export const ADAPTIVE_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS adaptive_leases (lease_key TEXT PRIMARY KEY, holder_id TEXT NOT NULL, fence_token INTEGER NOT NULL, expires_at_ms INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS adaptive_ambient_state (guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, drive REAL NOT NULL CHECK(drive >= 0 AND drive <= 1), version INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL, pressure REAL NOT NULL DEFAULT 0, pressure_updated_at_ms INTEGER, speak_streak INTEGER NOT NULL DEFAULT 0, skip_streak INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(guild_id, channel_id));
CREATE TABLE IF NOT EXISTS adaptive_ambient_audits (id INTEGER PRIMARY KEY AUTOINCREMENT, event_id TEXT NOT NULL, guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, outcome TEXT NOT NULL, diagnostic TEXT, proposal_json TEXT, recorded_at_ms INTEGER NOT NULL, evidence_weight REAL, probability REAL, draw REAL, drive_before REAL, drive_after REAL, active_human_count INTEGER, roster_fresh INTEGER, UNIQUE(event_id, guild_id, channel_id));
CREATE TABLE IF NOT EXISTS adaptive_relationship_profiles (guild_id TEXT NOT NULL, channel_id TEXT NOT NULL DEFAULT '', user_id TEXT NOT NULL, rapport REAL NOT NULL DEFAULT 0.5, familiarity REAL NOT NULL DEFAULT 0.5, notes_json TEXT NOT NULL DEFAULT '[]', updated_at_ms INTEGER NOT NULL, PRIMARY KEY(guild_id, user_id));
CREATE TABLE IF NOT EXISTS adaptive_relationship_ledger (event_id TEXT NOT NULL, user_id TEXT NOT NULL, proposal_index INTEGER NOT NULL, guild_id TEXT NOT NULL, channel_id TEXT NOT NULL DEFAULT '', rapport_delta REAL NOT NULL, familiarity_delta REAL NOT NULL, notes_json TEXT NOT NULL, created_at_ms INTEGER NOT NULL, PRIMARY KEY(event_id, user_id, proposal_index));
CREATE TABLE IF NOT EXISTS adaptive_budgets (scope_key TEXT NOT NULL, budget_key TEXT NOT NULL, count INTEGER NOT NULL, window_start_ms INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL, PRIMARY KEY(scope_key, budget_key));
CREATE TABLE IF NOT EXISTS conversation_archive_batches (batch_key TEXT PRIMARY KEY, scope_id TEXT NOT NULL, source_start_id INTEGER NOT NULL, source_end_id INTEGER NOT NULL, source_event_ids_json TEXT NOT NULL DEFAULT '[]', summary_key TEXT NOT NULL UNIQUE, status TEXT NOT NULL, claim_holder_id TEXT, claim_fence_token INTEGER, claim_expires_at_ms INTEGER, attempt_count INTEGER NOT NULL DEFAULT 0, provider_diagnostic TEXT, next_attempt_at_ms INTEGER, created_at_ms INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_archive_batch_range ON conversation_archive_batches(scope_id, source_start_id, source_end_id);
CREATE TABLE IF NOT EXISTS conversation_archive_summaries (summary_key TEXT PRIMARY KEY, batch_key TEXT NOT NULL UNIQUE REFERENCES conversation_archive_batches(batch_key), summary TEXT NOT NULL, created_at_ms INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS conversation_raw_archive_markers (raw_event_id INTEGER PRIMARY KEY REFERENCES conversation_raw_events(id), batch_key TEXT NOT NULL REFERENCES conversation_archive_batches(batch_key), archived_at_ms INTEGER NOT NULL, UNIQUE(batch_key, raw_event_id));
CREATE TABLE IF NOT EXISTS discord_membership_snapshots (guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, member_ids_json TEXT NOT NULL, complete INTEGER NOT NULL CHECK(complete IN (0,1)), observed_at_ms INTEGER NOT NULL, holder_id TEXT NOT NULL, fence_token INTEGER NOT NULL, PRIMARY KEY(guild_id, channel_id));
CREATE TABLE IF NOT EXISTS participant_poll_cursors (guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, message_id TEXT NOT NULL, updated_at_ms INTEGER NOT NULL, PRIMARY KEY(guild_id, channel_id));
CREATE TABLE IF NOT EXISTS participant_worker_diagnostics (id INTEGER PRIMARY KEY AUTOINCREMENT, lease_key TEXT NOT NULL, holder_id TEXT NOT NULL, fence_token INTEGER NOT NULL, diagnostic TEXT NOT NULL, recorded_at_ms INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS participant_event_work (id TEXT PRIMARY KEY, event_id TEXT NOT NULL, event_digest TEXT NOT NULL, guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, status TEXT NOT NULL, observe_only INTEGER NOT NULL, claim_holder_id TEXT, claim_fence_token INTEGER, claim_expires_at_ms INTEGER, created_at_ms INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL, UNIQUE(event_id, guild_id, channel_id));
CREATE TABLE IF NOT EXISTS participant_delivery_plans (id TEXT PRIMARY KEY, work_id TEXT NOT NULL UNIQUE REFERENCES participant_event_work(id), guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, status TEXT NOT NULL, created_at_ms INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS participant_delivery_chunks (plan_id TEXT NOT NULL REFERENCES participant_delivery_plans(id), chunk_index INTEGER NOT NULL, content TEXT NOT NULL, nonce TEXT NOT NULL UNIQUE, PRIMARY KEY(plan_id, chunk_index));
CREATE TABLE IF NOT EXISTS participant_delivery_receipts (plan_id TEXT NOT NULL, chunk_index INTEGER NOT NULL, nonce TEXT NOT NULL UNIQUE, discord_message_id TEXT NOT NULL, received_at_ms INTEGER NOT NULL, PRIMARY KEY(plan_id, chunk_index), FOREIGN KEY(plan_id, chunk_index) REFERENCES participant_delivery_chunks(plan_id, chunk_index));
`;
