export const ADAPTIVE_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS conversation_participation_ticks (
  id TEXT PRIMARY KEY, guild_id TEXT NOT NULL, channel_id TEXT NOT NULL,
  mode TEXT NOT NULL CHECK(mode IN ('apply','shadow')), primary_contract_version TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('bound','budget_wait','primary_claimed','primary_retry_wait','primary_invalid','primary_unavailable','context_truncated','snapshot_corrupt','decided','validation_claimed','validated','validation_unavailable','aborted')),
  anchor_work_id TEXT NOT NULL REFERENCES participant_event_work(id), snapshot_high_watermark_id INTEGER NOT NULL REFERENCES conversation_raw_events(id),
  snapshot_json TEXT NOT NULL, snapshot_utf8_bytes INTEGER NOT NULL CHECK(snapshot_utf8_bytes BETWEEN 2 AND 49152), snapshot_digest TEXT NOT NULL CHECK(length(snapshot_digest)=64),
  persona_source TEXT NOT NULL CHECK(persona_source IN ('channel_profile','configured_global','generic')), persona_text TEXT NOT NULL, persona_utf8_bytes INTEGER NOT NULL CHECK(persona_utf8_bytes BETWEEN 1 AND 8192), persona_digest TEXT NOT NULL CHECK(length(persona_digest)=64), persona_revision TEXT NOT NULL CHECK(length(persona_revision)=64),
  primary_attempt_count INTEGER NOT NULL DEFAULT 0 CHECK(primary_attempt_count BETWEEN 0 AND 3), primary_claim_holder_id TEXT, primary_claim_fence_token INTEGER, primary_claim_expires_at_ms INTEGER,
  primary_result_json TEXT, primary_result_utf8_bytes INTEGER, primary_result_digest TEXT, delivery_disposition TEXT CHECK(delivery_disposition IN ('pending','delivered','retryable','cancelled','not_applicable')), abort_reason TEXT CHECK(abort_reason IN ('scope_fence_lost','explicit_predecision')),
  created_at_ms INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL,
  CHECK ((status='primary_claimed') = (primary_claim_holder_id IS NOT NULL AND primary_claim_fence_token IS NOT NULL AND primary_claim_expires_at_ms IS NOT NULL)),
  CHECK (status='primary_claimed' OR (primary_claim_holder_id IS NULL AND primary_claim_fence_token IS NULL AND primary_claim_expires_at_ms IS NULL)),
  CHECK ((primary_result_json IS NULL AND primary_result_utf8_bytes IS NULL AND primary_result_digest IS NULL) OR (primary_result_json IS NOT NULL AND primary_result_utf8_bytes BETWEEN 1 AND 9216 AND primary_result_digest IS NOT NULL AND length(primary_result_digest)=64))
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_participation_tick_apply_anchor ON conversation_participation_ticks(anchor_work_id) WHERE mode='apply' AND status <> 'aborted';
CREATE INDEX IF NOT EXISTS idx_participation_ticks_scope_status ON conversation_participation_ticks(guild_id,channel_id,mode,status,created_at_ms,id);
CREATE TABLE IF NOT EXISTS conversation_participation_snapshot_turns (
  tick_id TEXT NOT NULL REFERENCES conversation_participation_ticks(id), ordinal INTEGER NOT NULL CHECK(ordinal BETWEEN 0 AND 119), raw_event_id INTEGER NOT NULL REFERENCES conversation_raw_events(id), content TEXT NOT NULL, content_utf8_bytes INTEGER NOT NULL CHECK(content_utf8_bytes BETWEEN 0 AND 8192), content_digest TEXT NOT NULL CHECK(length(content_digest)=64), PRIMARY KEY(tick_id,ordinal), UNIQUE(tick_id,raw_event_id)
);
CREATE TABLE IF NOT EXISTS conversation_participation_coverage (
  tick_id TEXT NOT NULL REFERENCES conversation_participation_ticks(id), work_id TEXT NOT NULL REFERENCES participant_event_work(id), coverage_kind TEXT NOT NULL CHECK(coverage_kind IN ('shadow','apply')), PRIMARY KEY(tick_id,work_id), UNIQUE(coverage_kind,work_id)
);
CREATE TABLE IF NOT EXISTS conversation_participation_primary_chunks (
  tick_id TEXT NOT NULL REFERENCES conversation_participation_ticks(id), chunk_index INTEGER NOT NULL CHECK(chunk_index BETWEEN 0 AND 4), content TEXT NOT NULL, content_utf8_bytes INTEGER NOT NULL CHECK(content_utf8_bytes BETWEEN 1 AND 1800), content_digest TEXT NOT NULL CHECK(length(content_digest)=64), PRIMARY KEY(tick_id,chunk_index)
);
CREATE TABLE IF NOT EXISTS conversation_participation_validations (
  tick_id TEXT PRIMARY KEY REFERENCES conversation_participation_ticks(id), status TEXT NOT NULL CHECK(status IN ('pending','claimed','applied','accepted_shadow','unavailable')), schema_version TEXT NOT NULL, model TEXT NOT NULL, claim_holder_id TEXT, claim_fence_token INTEGER, claim_expires_at_ms INTEGER, attempt_count INTEGER NOT NULL DEFAULT 0 CHECK(attempt_count BETWEEN 0 AND 3), missed_opportunity REAL CHECK(missed_opportunity BETWEEN 0 AND 1), interruption REAL CHECK(interruption BETWEEN 0 AND 1), confidence REAL CHECK(confidence BETWEEN 0 AND 1), prior_delta REAL CHECK(prior_delta BETWEEN -0.05 AND 0.05), rationale TEXT, rationale_utf8_bytes INTEGER CHECK(rationale_utf8_bytes BETWEEN 1 AND 2000), prior_before REAL CHECK(prior_before BETWEEN -0.25 AND 0.25), prior_after REAL CHECK(prior_after BETWEEN -0.25 AND 0.25), prior_version_before INTEGER, prior_version_after INTEGER, created_at_ms INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL,
  CHECK ((status='claimed') = (claim_holder_id IS NOT NULL AND claim_fence_token IS NOT NULL AND claim_expires_at_ms IS NOT NULL)),
  CHECK (status='claimed' OR (claim_holder_id IS NULL AND claim_fence_token IS NULL AND claim_expires_at_ms IS NULL)),
  CHECK ((status IN ('pending','claimed','unavailable') AND missed_opportunity IS NULL AND interruption IS NULL AND confidence IS NULL AND prior_delta IS NULL AND rationale IS NULL AND rationale_utf8_bytes IS NULL AND prior_before IS NULL AND prior_after IS NULL AND prior_version_before IS NULL AND prior_version_after IS NULL) OR (status='applied' AND missed_opportunity IS NOT NULL AND interruption IS NOT NULL AND confidence IS NOT NULL AND prior_delta IS NOT NULL AND rationale IS NOT NULL AND rationale_utf8_bytes IS NOT NULL AND prior_before IS NOT NULL AND prior_after IS NOT NULL AND prior_version_before IS NOT NULL AND prior_version_after IS NOT NULL) OR (status='accepted_shadow' AND missed_opportunity IS NOT NULL AND interruption IS NOT NULL AND confidence IS NOT NULL AND prior_delta IS NOT NULL AND rationale IS NOT NULL AND rationale_utf8_bytes IS NOT NULL AND prior_before IS NULL AND prior_after IS NULL AND prior_version_before IS NULL AND prior_version_after IS NULL))
);
CREATE INDEX IF NOT EXISTS idx_participation_validation_status ON conversation_participation_validations(status,created_at_ms,tick_id);
CREATE TABLE IF NOT EXISTS conversation_participation_priors (
  guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, persona_revision TEXT NOT NULL CHECK(length(persona_revision)=64), primary_contract_version TEXT NOT NULL, value REAL NOT NULL CHECK(value BETWEEN -0.25 AND 0.25), version INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL, PRIMARY KEY(guild_id,channel_id,persona_revision,primary_contract_version)
);
CREATE TABLE IF NOT EXISTS conversation_participation_mode_state (
  guild_id TEXT NOT NULL, channel_id TEXT NOT NULL,
  mode TEXT NOT NULL CHECK(mode IN ('off','shadow','apply')),
  changed_at_ms INTEGER NOT NULL,
  PRIMARY KEY(guild_id,channel_id)
);
CREATE TABLE IF NOT EXISTS adaptive_leases (lease_key TEXT PRIMARY KEY, holder_id TEXT NOT NULL, fence_token INTEGER NOT NULL, expires_at_ms INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS adaptive_ambient_state (guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, drive REAL NOT NULL CHECK(drive >= 0 AND drive <= 1), version INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL, pressure REAL NOT NULL DEFAULT 0, pressure_updated_at_ms INTEGER, speak_streak INTEGER NOT NULL DEFAULT 0, skip_streak INTEGER NOT NULL DEFAULT 0, PRIMARY KEY(guild_id, channel_id));
CREATE TABLE IF NOT EXISTS adaptive_ambient_audits (id INTEGER PRIMARY KEY AUTOINCREMENT, event_id TEXT NOT NULL, guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, outcome TEXT NOT NULL, diagnostic TEXT, proposal_json TEXT, recorded_at_ms INTEGER NOT NULL, evidence_weight REAL, probability REAL, draw REAL, drive_before REAL, drive_after REAL, active_human_count INTEGER, roster_fresh INTEGER, UNIQUE(event_id, guild_id, channel_id));
CREATE TABLE IF NOT EXISTS adaptive_relationship_profiles (guild_id TEXT NOT NULL, channel_id TEXT NOT NULL DEFAULT '', user_id TEXT NOT NULL, rapport REAL NOT NULL DEFAULT 0.5, familiarity REAL NOT NULL DEFAULT 0.5, notes_json TEXT NOT NULL DEFAULT '[]', updated_at_ms INTEGER NOT NULL, PRIMARY KEY(guild_id, user_id));
CREATE TABLE IF NOT EXISTS adaptive_relationship_ledger (event_id TEXT NOT NULL, user_id TEXT NOT NULL, proposal_index INTEGER NOT NULL, guild_id TEXT NOT NULL, channel_id TEXT NOT NULL DEFAULT '', rapport_delta REAL NOT NULL, familiarity_delta REAL NOT NULL, notes_json TEXT NOT NULL, created_at_ms INTEGER NOT NULL, PRIMARY KEY(event_id, user_id, proposal_index));
CREATE TABLE IF NOT EXISTS adaptive_budgets (scope_key TEXT NOT NULL, budget_key TEXT NOT NULL, count INTEGER NOT NULL, window_start_ms INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL, PRIMARY KEY(scope_key, budget_key));
CREATE TABLE IF NOT EXISTS conversation_archive_batches (batch_key TEXT PRIMARY KEY, scope_id TEXT NOT NULL, source_start_id INTEGER NOT NULL, source_end_id INTEGER NOT NULL, source_event_ids_json TEXT NOT NULL DEFAULT '[]', summary_key TEXT NOT NULL UNIQUE, status TEXT NOT NULL, claim_holder_id TEXT, claim_fence_token INTEGER, claim_expires_at_ms INTEGER, attempt_count INTEGER NOT NULL DEFAULT 0, provider_diagnostic TEXT, next_attempt_at_ms INTEGER, created_at_ms INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_archive_batch_range ON conversation_archive_batches(scope_id, source_start_id, source_end_id);
CREATE TABLE IF NOT EXISTS conversation_archive_summaries (summary_key TEXT PRIMARY KEY, batch_key TEXT NOT NULL UNIQUE REFERENCES conversation_archive_batches(batch_key), summary TEXT NOT NULL, created_at_ms INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS conversation_raw_archive_markers (raw_event_id INTEGER PRIMARY KEY REFERENCES conversation_raw_events(id), batch_key TEXT NOT NULL REFERENCES conversation_archive_batches(batch_key), archived_at_ms INTEGER NOT NULL, UNIQUE(batch_key, raw_event_id));
CREATE TABLE IF NOT EXISTS discord_membership_snapshots (guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, member_ids_json TEXT NOT NULL, complete INTEGER NOT NULL CHECK(complete IN (0,1)), observed_at_ms INTEGER NOT NULL, holder_id TEXT NOT NULL, fence_token INTEGER NOT NULL, PRIMARY KEY(guild_id, channel_id));
CREATE TABLE IF NOT EXISTS participant_poll_cursors (guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, message_id TEXT NOT NULL, updated_at_ms INTEGER NOT NULL, PRIMARY KEY(guild_id, channel_id));
CREATE TABLE IF NOT EXISTS participant_worker_diagnostics (id INTEGER PRIMARY KEY AUTOINCREMENT, lease_key TEXT NOT NULL, holder_id TEXT NOT NULL, fence_token INTEGER NOT NULL, diagnostic TEXT NOT NULL, recorded_at_ms INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS participant_event_work (id TEXT PRIMARY KEY, event_id TEXT NOT NULL, event_digest TEXT NOT NULL, guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, status TEXT NOT NULL, observe_only INTEGER NOT NULL, claim_holder_id TEXT, claim_fence_token INTEGER, claim_expires_at_ms INTEGER, created_at_ms INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL, UNIQUE(event_id, guild_id, channel_id));
CREATE TABLE IF NOT EXISTS participant_delivery_plans (id TEXT PRIMARY KEY, work_id TEXT NOT NULL UNIQUE REFERENCES participant_event_work(id), guild_id TEXT NOT NULL, channel_id TEXT NOT NULL, status TEXT NOT NULL, created_at_ms INTEGER NOT NULL, updated_at_ms INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS participant_delivery_chunks (plan_id TEXT NOT NULL REFERENCES participant_delivery_plans(id), chunk_index INTEGER NOT NULL, content TEXT NOT NULL, nonce TEXT NOT NULL UNIQUE, PRIMARY KEY(plan_id, chunk_index));
CREATE TABLE IF NOT EXISTS participant_delivery_receipts (plan_id TEXT NOT NULL, chunk_index INTEGER NOT NULL, nonce TEXT NOT NULL UNIQUE, discord_message_id TEXT NOT NULL, received_at_ms INTEGER NOT NULL, PRIMARY KEY(plan_id, chunk_index), FOREIGN KEY(plan_id, chunk_index) REFERENCES participant_delivery_chunks(plan_id, chunk_index));
`;
